//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_MauBaocao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NV_MauBaocao()
        {
            this.NV_MaubaocaoDiadanh = new HashSet<NV_MaubaocaoDiadanh>();
            this.NV_MaubaocaoThuoctinh = new HashSet<NV_MaubaocaoThuoctinh>();
        }
    
        public string MauBC_ID { get; set; }
        public string TenBaocao { get; set; }
        public System.DateTime Ngaylap { get; set; }
        public string Diadanh_ID { get; set; }
        public string Nhansu_ID { get; set; }
        public bool Trangthai { get; set; }
        public int STT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NV_MaubaocaoDiadanh> NV_MaubaocaoDiadanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NV_MaubaocaoThuoctinh> NV_MaubaocaoThuoctinh { get; set; }
    }
}
