//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Danhmuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TD_Danhmuc()
        {
            this.TD_Diadanh = new HashSet<TD_Diadanh>();
        }
    
        public string Danhmuc_ID { get; set; }
        public string TenDanhmuc { get; set; }
        public string Danhmuccha_ID { get; set; }
        public bool Trangthai { get; set; }
        public string STT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_Diadanh> TD_Diadanh { get; set; }
    }
}
