//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Diadanh
    {
        public string Diadanh_ID { get; set; }
        public string Tendiadanh { get; set; }
        public string Diadanhcha_ID { get; set; }
        public string Mota { get; set; }
        public string ToadoX { get; set; }
        public string ToadoY { get; set; }
        public string URLs { get; set; }
        public bool Trangthai { get; set; }
        public string Danhmuc_ID { get; set; }
        public Nullable<int> STT { get; set; }
    
        public virtual TD_Danhmuc TD_Danhmuc { get; set; }
    }
}
