//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_Nguoidung
    {
        public string NhanSu_ID { get; set; }
        public string ten { get; set; }
        public string hoDem { get; set; }
        public string fullName { get; set; }
        public string diaChi { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
        public string tenTruyCap { get; set; }
        public string matKhau { get; set; }
        public string anhDaiDien { get; set; }
        public string anhThumb { get; set; }
        public int gioiTinh { get; set; }
        public Nullable<int> Quyensudung { get; set; }
        public bool Trangthai { get; set; }
        public Nullable<int> STT { get; set; }
    }
}
