//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_Dulieudubao
    {
        public string SolieuDB_ID { get; set; }
        public System.DateTime Ngaydubao { get; set; }
        public string BaocaoDiadanh_ID { get; set; }
        public string BaocaoThuoctinh_ID { get; set; }
        public double Giatri { get; set; }
    }
}
