//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_MaubaocaoDiadanh
    {
        public string BaocaoDiadanh_ID { get; set; }
        public string MauBC_ID { get; set; }
        public string Diadanh_ID { get; set; }
        public Nullable<int> STT { get; set; }
    
        public virtual NV_MauBaocao NV_MauBaocao { get; set; }
    }
}
