//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_MaubaocaoThuoctinh
    {
        public string BaocaoThuoctinh_ID { get; set; }
        public string MauBC_ID { get; set; }
        public string Thuoctinh_ID { get; set; }
        public int STT { get; set; }
    
        public virtual NV_MauBaocao NV_MauBaocao { get; set; }
        public virtual TD_Thuoctinh TD_Thuoctinh { get; set; }
    }
}
