//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_ThuoctinhGiatri
    {
        public string ThuoctinhGiatri_ID { get; set; }
        public string Thuoctinh_ID { get; set; }
        public string TenGiatri { get; set; }
        public Nullable<double> GiatriMin { get; set; }
        public Nullable<double> GiatriMax { get; set; }
        public bool Trangthai { get; set; }
        public int STT { get; set; }
    
        public virtual TD_Thuoctinh TD_Thuoctinh { get; set; }
    }
}
