//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Thuoctinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TD_Thuoctinh()
        {
            this.NV_MaubaocaoThuoctinh = new HashSet<NV_MaubaocaoThuoctinh>();
            this.TD_ThuoctinhGiatri = new HashSet<TD_ThuoctinhGiatri>();
        }
    
        public string Thuoctinh_ID { get; set; }
        public string Tenthuoctinh { get; set; }
        public string Donvitinh { get; set; }
        public bool Trangthai { get; set; }
        public int STT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NV_MaubaocaoThuoctinh> NV_MaubaocaoThuoctinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_ThuoctinhGiatri> TD_ThuoctinhGiatri { get; set; }
    }
}
